### ISSUE TITLE
execl()

### ISSUE THREAD

**Issue by textbrowser** [maandree/krandom#1]
The argv argument should be examined before use.

For example,

execl("krandom", arg, (char *) 0);

may produce undesired behavior if arg is accidentally zero.

**Comment by maandree** [comment]
I don't have any exec calls. And argv is only used for printing the name of command (as called), and parsing the command line.
I am not sure what you mean can go wrong. Well if argc is 0, either will happen: "(null)" will be printed instead if the command name, gibbrish will be printed instead of the command name, program will segfault or otherwise be killed by the OS kernel. Hardly a problem of such an unlikely event.

**Comment by textbrowser** [comment]
Sorry for not providing more information. I have an external program that issues an execl(). At times, krandom dies because the second argument to execl() is zero. The death is my undesired behavior. Would it be possible for it to exit more calmly? :-)

**Comment by maandree** [comment]
You should never (I think) exec without any arguments, but I will fix it.

**Comment by textbrowser** [comment]
Indeed. But then you may never discover interesting results.
Perhaps the exec() families should be more inquisitive about the arguments.
